proyecto_final_moha_nestor/Controllers/ContactanosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proyecto_final_moha_nestor.Controllers
{
    public class ContactanosController : Controller
    {
        // GET: Contactanos
        public ActionResult Index()
        {
            return View();
        }
    }
}

proyecto_final_moha_nestor/Controllers/gamesController.cs
using proyecto_final_moha_nestor.logic;
using proyecto_final_moha_nestor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace proyecto_final_moha_nestor.Controllers
{
    public class gamesController : Controller
    {
        //GET: index
        public ActionResult Index()
        {
            return View();
        }

        // GET: g2048
        public ActionResult g2048()
        {
            return View();
        }

        // GET: arcanoid
        [HttpGet]
        public ActionResult arcanoid()
        {
            return View();
        }

        // POST: arcanoid
        [HttpPost]
        public  string arcanoid(recordjson recordjs)
        {
            if(!ModelState.IsValid)
            {
                //agregar error de no poderse guardar
                return "{\"status\":\"fail\" }";
            }
            else
            {
                var record = conversor.convertir(recordjs);
                DataSaver.SaveData(record);
                return "{\"status\":\"correct\" }";
            }
            
        }

		// POST: g2048
		[HttpPost]
		public string g2048(recordjson recordjs)
		{
			if (!ModelState.IsValid)
			{
				//agregar error de no poderse guardar
				return "{\"status\":\"fail\" }";
			}
			else
			{
				var record = conversor.convertir(recordjs);
				DataSaver.SaveData(record);
				return "{\"status\":\"correct\" }";
			}

		}
	}
}

proyecto_final_moha_nestor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Retroverse", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
			@Html.Partial("_NotLogged")
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Proyecto final DAW</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

proyecto_final_moha_nestor/Views/Shared/_NotLogged.cshtml
@{
    ViewBag.Title = "_NotLogged";
}

<div class="navbar-collapse collapse">
@if (Request.IsAuthenticated)
{
	<ul class="nav navbar-nav">
		<li>@Html.ActionLink("Home", "Index", "Home")</li>
		<li>@Html.ActionLink("Juegos", "Index", "games")</li>
		<li>@Html.ActionLink("Records", "Index", "Records")</li>
        <li>@Html.ActionLink("Contáctanos", "Index", "Contactanos")</li>
	</ul>
	@Html.Partial("_LoginPartial")
}
else
{
}
</div>

proyecto_final_moha_nestor/Views/Shared/_NotSupported.cshtml
@{
    ViewBag.Title = "_NotSupported";
}

<h2>Lo lamentamos pero este juego no está disponible para dispositivos móviles</h2>

proyecto_final_moha_nestor/Views/Shared/_indice_log_register.cshtml
@{
    ViewBag.Title = "_indice_log_register";
}

<div id="index">
	<h1 id="titulo_general">Bienvenido a Retroverse</h1>
	<a class="effect" href="~/Account/Login">Login</a>
	<a class="effect" href="~/Account/Register">Registro</a>
</div>